export const CREATE_ADDRESS = "CREATE_ADDRESS";
export const RETRIEVE_ADDRESS = "RETRIEVE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const DELETE_ALL_ADDRESS = "DELETE_ALL_ADDRESS";